name = "tsf-vms-flutter"
compatibility_date = "2024-09-23"
pages_build_output_dir = "build/web"
functions = "./functions"

# We use `wrangler pages publish build/web` in CI to publish static assets.
# Remove `assets` here to avoid Wrangler validating the directory before CI builds it.

